cache:
  paths:
    - target/
    - node_modules/
    
stages:
  - test
  - build

rust:test:
  stage: test
  image: softprops/lambda-rust:latest
  before_script:
    - rustc --version && cargo --version
    - rustup update
    - rustup component add clippy
  script:
    - cargo check
    - cargo test --verbose
    - cargo clippy --all-targets --all-features -- -D warnings

deploy:
  stage: build
  image: circleci/node:lts
  variables:
      DOCKER_HOST: "tcp://docker:2375"
      DOCKER_DRIVER: overlay
  services:
    - docker:dind
  before_script:
    - npm i
  script:
    - npm run build:js
    - npm run deploy