cache:
  paths:
    - target/
    - node_modules/
    
stages:
  - test
  - build

rust:clippy:
  stage: test
  image: rust:latest
  before_script:
    - rustc --version && cargo --version
    - rustup update
    - rustup component add clippy
  script:
    - cargo clippy --all-targets --all-features -- -D warnings

rust:test:
  stage: test
  image: rust:latest
  before_script:
    - rustc --version && cargo --version
    - rustup update
  script:
    - cargo test --verbose

rust:build:
  stage: test
  image: rust:latest
  before_script:
    - rustc --version && cargo --version
    - rustup update
  script:
    - cargo build --verbose

deploy:
  stage: build
  image: node:lts
  services:
    - docker:dind
  before_script:
    - npm ci
  script:
    - npm run build:js
    - npm run deploy