# for more information on configuring a rust travis build
# see https://docs.travis-ci.com/user/languages/rust/
language: node_js
node_js:
  - "lts/*"

# only build pushes to master
# prs are build separately
# https://docs.travis-ci.com/user/pull-requests/#how-pull-requests-are-built
branches:
  only:
    - master

cache: npm

script:
  # package application here to cache build artifacts for future build/deploys
  - npm ci
  - npm run build:js
  - npx serverless package

# deploy on pushes to master branch
# assumes aws credentials (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)
# are configured in travis settings
# see https://serverless.com/framework/docs/providers/aws/guide/credentials/
# for more information
deploy:
  - provider: script
    script: npx serverless deploy --conceal
    skip_cleanup: true
    on:
      branch: master

notifications:
  email:
    on_success: always
