[package]
name = "dice-roller"
version = "0.1.0"
authors = ["Ben Brandt <benjamin.j.brandt@gmail.com>"]
edition = "2018"

[dependencies]
lambda_runtime = "0.1"
rand = "0.6"
regex = "1"
serde_json = "1.0"
