[package]
name = "dice-roller"
version = "0.1.0"
authors = ["Ben Brandt <benjamin.j.brandt@gmail.com>"]
edition = "2018"

[dependencies]
http = "*"
lambda_http = "*"
lambda_runtime = "*"
log = "*"
rand = "*"
regex = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
simple_logger = "*"
