[package]
name = "dice-roller"
version = "0.1.0"
authors = ["Ben Brandt <benjamin.j.brandt@gmail.com>"]
edition = "2018"

[dependencies]
lambda_http = "0.1"
lambda_runtime = "0.2"
log = "0.4"
rand = "0.6"
regex = "1"
serde = "1"
serde_derive = "1"
serde_json = "1"
simple_logger = "1"
